wallpaper {
	monitor = eDP-1
	path = /home/himakun/Pictures/wallpapers/gruvbox_tux.png
	fit_mode = cover
}

wallpaper {
	monitor = HDMI-A-1
	path = /home/himakun/Pictures/wallpapers/gruvbox_tux.png
	fit_mode = cover
}
